IF (NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'Auth')) 
BEGIN
    EXEC ('CREATE SCHEMA [Auth] AUTHORIZATION [dbo]')
END


CREATE TABLE [Auth].[User]
(
	[Id] INT IDENTITY,
	[Username] VARCHAR(255) NOT NULL,
	[Password] VARCHAR(255) NOT NULL,
	[Email] VARCHAR(255) NOT NULL

	CONSTRAINT PK_USER PRIMARY KEY(Id),
	CONSTRAINT UQ_USERNAME UNIQUE(Username),
	CONSTRAINT UQ_EMAIL UNIQUE(Email)
)