IF (NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'Arduino')) 
BEGIN
    EXEC ('CREATE SCHEMA [Arduino] AUTHORIZATION [dbo]')
END

CREATE TABLE [Arduino].[Config]
(
	[Id] INT IDENTITY,
	[Key] VARCHAR(255) NOT NULL,
	[Value] VARCHAR(MAX) NOT NULL,
	[DESC] VARCHAR(255)

	CONSTRAINT PK_CONFIG PRIMARY KEY(Id),
	CONSTRAINT UQ_KEY UNIQUE([Key])
)